# Generated by Django 3.2.5 on 2021-07-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_alter_activity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autres", "Autres"),
                    ("base-de-donnees", "Base de données"),
                    ("developpement-back-end", "Développement Back-end"),
                    ("developpement-front-end", "Développement Front-end"),
                    ("developpement-full-stack", "Développement Full-Stack"),
                    ("gestion-de-projet", "Gestion de projet"),
                    (
                        "gestion-de-site-reseaux-sociaux",
                        "Gestion de site & réseaux sociaux",
                    ),
                    ("marketing", "Marketing"),
                    ("produit", "Produit"),
                    ("pedagogie-formation", "Pédagogie & formation"),
                    ("seosea", "SEO/SEA"),
                    ("support", "Support"),
                    ("systeme", "Système"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
