# Generated by Django 3.2.5 on 2021-07-13 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_alter_activity_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("hour_per_session", models.PositiveSmallIntegerField()),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ponctuel", "Ponctuel"),
                            ("journalier", "Chaque jour"),
                            ("hebdomadaire", "Chaque semaine"),
                            ("quinzomadaire", "Toutes les 2 semaines"),
                            ("mensuel", "Chaque mois"),
                            ("bimestriel", "Tous les 2 mois"),
                            ("trimestriel", "Chaque trimestre"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
