# Generated by Django 3.2.5 on 2021-07-15 12:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidate", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),  # noqa: E501
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",  # noqa: E501
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        verbose_name="email address",  # noqa: E501
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BENEVOLE", "Un bénévole"),
                            ("ASSOCIATION", "Une association"),
                        ],
                        max_length=25,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",  # noqa: E501
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=500)),
                ("web_site_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("gitlab_url", models.URLField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        default="default.jpg", upload_to="candidate"
                    ),  # noqa: E501
                ),
                ("activity", models.ManyToManyField(to="candidate.Activity")),
                (
                    "availability",
                    models.ManyToManyField(to="candidate.Availability"),
                ),  # noqa: E501
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_1", models.CharField(blank=True, max_length=250)),
                ("address_2", models.CharField(blank=True, max_length=250)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entitled",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASH", "Action sociale, Santé, Humanitaire"),
                            ("CL", "Culture et loisirs"),
                            ("DD", "Défense des droits"),
                            ("EFI", "Education, Formation, Insertion"),
                            ("S", "Sports"),
                            ("A", "Autres"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),  # noqa: E501
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("remote", models.BooleanField(default=False)),
                (
                    "scoop",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("city", "Local"),
                            ("department", "Départemental"),
                            ("region", "Régional"),
                            ("country", "National"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.candidateprofile",
                    ),
                ),
                ("sector", models.ManyToManyField(to="users.Sector")),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denomination", models.CharField(blank=True, max_length=50)),
                ("rna_code", models.CharField(blank=True, max_length=10)),
                ("siret_code", models.CharField(blank=True, max_length=14)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("web_site_url", models.URLField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField(blank=True, max_length=500)),
                (
                    "logo",
                    models.ImageField(
                        default="default.jpg", upload_to="organization"
                    ),  # noqa: E501
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_location",
                        related_query_name="organization_location",
                        to="users.location",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sector",
                        related_query_name="sector",
                        to="users.sector",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_location",
                related_query_name="candidate_location",
                to="users.location",
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,  # noqa: E501
            ),
        ),
    ]
