# Generated by Django 3.2.5 on 2021-07-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='activity',
            field=models.ManyToManyField(to='candidate.Activity'),
        ),
    ]
