# Generated by Django 3.2.5 on 2021-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_availability'),
        ('users', '0002_candidateprofile_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='availability',
            field=models.ManyToManyField(to='candidate.Availability'),
        ),
    ]
