# Generated by Django 3.2.5 on 2021-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_candidateprofile_organizationprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="avatar",
            field=models.ImageField(
                default="default.jpg", upload_to="candidate"
            ),  # noqa: E501
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="logo",
            field=models.ImageField(
                default="default.jpg", upload_to="organization"
            ),  # noqa: E501
        ),
    ]
